// =============================================================================
// Sprite — strip-sheet animation player (docs/fx-rn-port-plan.md, decision D2).
//
// A sprite = a fixed frame-size View (overflow hidden) containing the whole
// horizontal strip Image, translated left by −frameIndex × frameWidth so
// exactly one frame shows through the window. frameIndex is derived from a
// Reanimated shared value animated ON THE UI THREAD (withRepeat(withTiming)
// for loops; a single withTiming for one-shot attack/special plays), so React
// NEVER re-renders per frame — that zero-re-render property is the entire
// point of D2 (8 heroes × 12fps via setState would be a re-render storm).
// On react-native-web there is no separate UI thread; Reanimated drives the
// same worklet via requestAnimationFrame, still outside React's render loop.
//
// Frame geometry (frames / w / h) comes from the packed-strip manifest — frame
// sizes VARY per animation (64–256px), never assume one. Strips + manifest are
// generated by `npm run pack-sprites` (decision D1).
// =============================================================================
import { useCallback, useEffect, useRef } from "react";
import { View, type StyleProp, type ViewStyle } from "react-native";
import Animated, {
  Easing,
  cancelAnimation,
  useAnimatedStyle,
  useSharedValue,
  withRepeat,
  withTiming,
} from "react-native-reanimated";
import { scheduleOnRN } from "react-native-worklets";
import { SPRITES, type SpriteKey } from "./spriteMap";
import manifestJson from "./sprites/manifest.json";

interface ManifestEntry {
  frames: number;
  w: number;
  h: number;
  file: string;
}

// The generated manifest keys mirror SpriteKey exactly (both codegen'd by
// scripts/pack-sprites.mjs from the same walk); the cast just narrows the
// wide JSON-literal type down to that shared contract.
const MANIFEST = manifestJson as Record<SpriteKey, ManifestEntry>;

export interface SpriteProps {
  /** Which packed strip to play, e.g. "warrior/5_warlord/idle". */
  animKey: SpriteKey;
  /** Playback rate in frames per second (preview parity: idle 6, attack/special 12). */
  fps: number;
  /**
   * true → repeat forever (idle/rest). false → play once, hold the LAST frame,
   * then fire onDone (attack/special-style plays).
   */
  loop?: boolean;
  /**
   * Restart token for one-shots: bump it (e.g. a counter) to replay the same
   * animKey from frame 0 even when no other prop changed.
   */
  playKey?: number | string;
  /** One-shot completion callback (scheduled back onto the JS/React thread). */
  onDone?: () => void;
  /** Extra styles for the outer frame-window View (positioning, transforms). */
  style?: StyleProp<ViewStyle>;
}

export function Sprite({
  animKey,
  fps,
  loop = true,
  playKey,
  onDone,
  style,
}: SpriteProps) {
  const { frames, w, h } = MANIFEST[animKey];

  // progress runs 0 → frames in real time; the worklet below floors it into a
  // discrete frame index. Animating a continuous value and quantizing on the
  // UI thread is what keeps frame-stepping off the React render path (D2).
  const progress = useSharedValue(0);

  // Latest-onDone ref so the UI-thread completion callback never captures a
  // stale closure, and so a re-created onDone doesn't restart the animation.
  const onDoneRef = useRef(onDone);
  onDoneRef.current = onDone;
  const fireDone = useCallback(() => {
    onDoneRef.current?.();
  }, []);

  useEffect(() => {
    cancelAnimation(progress);
    progress.value = 0;
    const durationMs = (frames / fps) * 1000;
    if (loop) {
      progress.value = withRepeat(
        withTiming(frames, { duration: durationMs, easing: Easing.linear }),
        -1,
        false,
      );
    } else {
      progress.value = withTiming(
        frames,
        { duration: durationMs, easing: Easing.linear },
        (finished) => {
          "worklet";
          // Completion runs on the UI thread; hop back to the JS thread for
          // the React-side callback (mode switch back to idle, etc.).
          if (finished) scheduleOnRN(fireDone);
        },
      );
    }
    return () => cancelAnimation(progress);
    // playKey is a restart token: including it re-runs this effect (replay
    // from frame 0) even when animKey/fps/loop are unchanged.
  }, [animKey, frames, fps, loop, playKey, progress, fireDone]);

  const stripStyle = useAnimatedStyle(() => {
    // Clamp to the last frame: a finished one-shot parks at progress ===
    // frames, which must show frame frames−1, not slide past the strip end.
    const frameIndex = Math.min(frames - 1, Math.floor(progress.value));
    return { transform: [{ translateX: -frameIndex * w }] };
    // `progress` MUST be in the deps: on web without the worklets Babel plugin
    // (this Expo web bundle), Reanimated subscribes the style updater to the
    // shared values found in the DEPS ARRAY (updater.__closure is empty) —
    // omit it and the strip renders frame 0 forever while the clock still
    // runs. Harmless on native (stable identity). Found during STR-20 verify.
  }, [progress, frames, w]);

  return (
    <View style={[{ width: w, height: h, overflow: "hidden" }, style]}>
      <Animated.Image
        source={SPRITES[animKey]}
        // Exact strip dimensions from the manifest; "stretch" is a no-op at
        // these sizes and avoids any contain/cover letterboxing surprises.
        style={[{ width: frames * w, height: h }, stripStyle]}
        resizeMode="stretch"
        fadeDuration={0}
      />
    </View>
  );
}

export default Sprite;
